[font]
size = 14.0 # Adjust this number to change your font size

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    # Map Ctrl+V to paste normally
    { key = "V", mods = "Control", action = "Paste" },

    # The multi-action sequence for Ctrl+C
    { key = "C", mods = "Control", action = "Copy" },
    { key = "C", mods = "Control", action = "ClearSelection" },
    { key = "C", mods = "Control", action = "ReceiveChar" }
]
