set-option -g prefix  C-b

# Enable mouse mode
set -g mouse on

# Start counting pane and window number at 1
set -g base-index 1
set -g renumber-windows on

setw -g mode-keys vi
setw -g pane-base-index 1

# Set escape time to 0
set -s escape-time 1

set -g focus-events on

set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:RGB"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi 'Home' send -X start-of-line
bind -T copy-mode-vi 'End'  send -X end-of-line

# tmux-sessionizer
bind-key f run-shell "tmux neww tmux-sessionizer"

# Kill other sessions
bind-key K run-shell "tmux-kill-other-sessions"

# Kill other windows
bind-key W run-shell "tmux-kill-other-windows"

# tmux-sessionizer
bind-key S run-shell "tmux neww tmux-session-switcher"

# tmux cheat sheet
bind-key i run-shell "tmux neww tmux-cht.sh"

# new window before current window
bind-key C run-shell "tmux new-window -b -t :"

# Custom sessions
bind-key D run-shell "tmux-sessionizer ~/.dotfiles"
bind-key V run-shell "tmux-sessionizer ~/.dotfiles/nvim/.config/nvim"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

set -g @override_copy_command "$HOME/.local/bin/utf8-yank"
# set -g @plugin 'thewtex/tmux-mem-cpu-load'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# set -g status-interval 2
# set -g status-left '#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]'
# set -g status-left-length 60
