set-option -g prefix  C-b

# Enable mouse mode
set -g mouse on

# Start counting pane and window number at 1
set -g base-index 1
set -g renumber-windows on

setw -g mode-keys vi
setw -g pane-base-index 1

# Set escape time to 0
set -s escape-time 1

set -g focus-events on

set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:RGB"

bind-key -T copy-mode-vi v send-keys -X begin-selection

# tmux-sessionizer
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# tmux cheat sheet
bind-key -r i run-shell "tmux neww tmux-cht.sh"

# Custom sessions
bind-key -r A run-shell "tmux-sessionizer ~/dev/personal-projects/auth"
bind-key -r D run-shell "tmux-sessionizer ~/.dotfiles"
bind-key -r N run-shell "tmux-sessionizer ~/dev/personal-projects/narwhals"
bind-key -r P run-shell "tmux-sessionizer ~/dev/plannning"
bind-key -r T run-shell "tmux-sessionizer ~/dev/personal-projects/npck-todos"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-urlview'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
